// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUZFLfD6GRmZPdz4mvXfr8S3ypCb_hzEA',
    appId: '1:351751265947:web:77ab614b779c1e734e703e',
    messagingSenderId: '351751265947',
    projectId: 'carrentaldatabase-17c25',
    authDomain: 'carrentaldatabase-17c25.firebaseapp.com',
    databaseURL: 'https://carrentaldatabase-17c25-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldatabase-17c25.appspot.com',
    measurementId: 'G-39NSFPJNGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_23sk2Eid2OYUD5TA0CiNfzHrh3N31dY',
    appId: '1:351751265947:android:8f87f23690ef1bb54e703e',
    messagingSenderId: '351751265947',
    projectId: 'carrentaldatabase-17c25',
    databaseURL: 'https://carrentaldatabase-17c25-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldatabase-17c25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjh3zTPkTNpXpKmAIX9DEE_5Q-Igy58P8',
    appId: '1:351751265947:ios:2f5eca70f35e070c4e703e',
    messagingSenderId: '351751265947',
    projectId: 'carrentaldatabase-17c25',
    databaseURL: 'https://carrentaldatabase-17c25-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldatabase-17c25.appspot.com',
    iosBundleId: 'com.example.carrentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjh3zTPkTNpXpKmAIX9DEE_5Q-Igy58P8',
    appId: '1:351751265947:ios:521e226ae4a4bfae4e703e',
    messagingSenderId: '351751265947',
    projectId: 'carrentaldatabase-17c25',
    databaseURL: 'https://carrentaldatabase-17c25-default-rtdb.firebaseio.com',
    storageBucket: 'carrentaldatabase-17c25.appspot.com',
    iosBundleId: 'com.example.carrentalApp.RunnerTests',
  );
}
